force-app/main/default/objects/Library_Book__c/Library_Book__c.object-meta.xml
<CustomObject>
    <label>Library Book</label>
    <nameField>
        <displayFormat>LB-{0000000}</displayFormat>
        <label>Library Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>Author of the book</description>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Library_Book__c/fields/Available_Copies__c.field-meta.xml
<CustomField>
    <fullName>Available_Copies__c</fullName>
    <description>Available copies of the book</description>
    <label>Available Copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Library_Book__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the book</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Library_Book__c/fields/Total_Copies__c.field-meta.xml
<CustomField>
    <fullName>Total_Copies__c</fullName>
    <description>Total copies of the book</description>
    <label>Total Copies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/Library_Book_Loan__c.object-meta.xml
<CustomObject>
    <label>Library Book Loan</label>
    <nameField>
        <displayFormat>LBL-{0000000}</displayFormat>
        <label>Library Book Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Library Book Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book_Loan__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Book borrowed</description>
    <label>Book</label>
    <referenceTo>Library_Book__c</referenceTo>
    <relationshipLabel>Library Book Loans</relationshipLabel>
    <relationshipName>Library_Book_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Borrower of the copy</description>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Library Book Loans</relationshipLabel>
    <relationshipName>Library_Book_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Loan_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_End_Date__c</fullName>
    <description>End date of the book loan</description>
    <label>Loan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Start_Date__c</fullName>
    <description>Start date of the book loan</description>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LibraryService.cls
public with sharing class LibraryService {

    @AuraEnabled
    public static List<Library_Book__c> searchBooks(String searchTerm){
        List<Library_Book__c> libraryBookList = new List<Library_Book__c>();

        try{
            String searchTermLike =  String.escapeSingleQuotes('%' + searchTerm + '%');
            libraryBookList = [SELECT Id, Title__c, Author__c, Available_Copies__c, Total_Copies__c FROM Library_Book__c WHERE Title__c LIKE :searchTermLike OR Author__c LIKE :searchTermLike LIMIT 20];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return libraryBookList;
    }

    @AuraEnabled
    public static void loanBook(List<Id> bookIds, Id borrowerId){
        List<Library_Book_Loan__c> bookLoansToInsert = new List<Library_Book_Loan__c>();

        try{
            for(Id bookId : bookIds){
                Library_Book_Loan__c libraryBookLoan = new Library_Book_Loan__c();
                libraryBookLoan.Borrower__c = borrowerId;
                libraryBookLoan.Book__c = bookId;
                libraryBookLoan.Loan_Start_Date__c = Date.today();

                bookLoansToInsert.add(libraryBookLoan);
            }

            insert bookLoansToInsert;

        }catch(Exception e){
            throw new AuraHandledException('No stock available');
        }       
    }

    @AuraEnabled
    public static void endBookLoan(Id bookLoanId){
        Library_Book_Loan__c libraryBookLoan = new Library_Book_Loan__c();
        libraryBookLoan.Id = bookLoanId;
        libraryBookLoan.Loan_End_Date__c = Date.today();

        update libraryBookLoan;
    }
}